(() => {
  const CFG = window.APRINCAR_GAME_CONFIG;
  const BRAND = window.APRINCAR_BRAND;
  const FONT = BRAND.fontFamily;
  const C = { bg: 0xf7f6f2, purple: 0x8b5cf6, blue: 0x2563eb, coral: 0xf43f5e, orange: 0xfb923c, sun: 0xfbcb24, leaf: 0x22c55e, sky: 0x38bdf8, ink: '#13203d', white: 0xffffff };
  const COLOR_HEX = { violet: C.purple, coral: C.coral, sun: C.sun, leaf: C.leaf, sky: C.sky };
  class AprincarScene extends Phaser.Scene {
    constructor() { super('main'); this.level = 1; this.attempts = 0; this.locked = false; }
    async create() {
      this.cameras.main.setBackgroundColor(C.bg); this.add.rectangle(480, 52, 960, 104, C.white).setStrokeStyle(1, 0xe2dfd7);
      BRAND.addPhaser(this, 22, 16);
      this.add.text(480, 20, CFG.name, { fontFamily: FONT, fontSize: '26px', fontStyle: 'bold', color: C.ink }).setOrigin(.5, 0);
      this.levelText = this.add.text(910, 28, 'Fase 1', { fontFamily: FONT, fontSize: '16px', fontStyle: 'bold', color: '#6f5bd7' }).setOrigin(1, 0);
      this.promptText = this.add.text(480, 118, '', { fontFamily: FONT, fontSize: '28px', fontStyle: 'bold', color: C.ink, align: 'center', wordWrap: { width: 820 } }).setOrigin(.5, 0);
      this.statusText = this.add.text(480, 570, '', { fontFamily: FONT, fontSize: '22px', fontStyle: 'bold', color: '#5143a6' }).setOrigin(.5); this.starText = this.add.text(32, 574, '⭐ 0', { fontFamily: FONT, fontSize: '20px', fontStyle: 'bold', color: '#6f5bd7' });
      await aprincar.session.start({ mode: CFG.mode }); this.nextRound();
    }
    updateState(values = {}) { if (window.__APRINCAR_GAME_STATE__) Object.assign(window.__APRINCAR_GAME_STATE__, values); }
    clearRound() { this.input.off('drag'); this.input.off('dragend'); this.input.off('pointerdown'); this.input.off('pointermove'); this.input.off('pointerup'); if (this.roundGroup) this.roundGroup.destroy(true); this.roundGroup = this.add.container(0, 0); this.statusText.setText(''); this.locked = false; this.attempts = 0; this.testTargets = []; this.challenge = null; }
    nextRound() { this.clearRound(); this.levelText.setText(`Fase ${this.level}`); const seed = (Date.now() % 100000) + this.level * 97; const rng = createSeededRandom(seed); if (CFG.mode === 'counting') this.setupCounting(generateCountingChallenge({ rng, seed, level: this.level, theme: CFG.variant })); if (CFG.mode === 'color') this.setupColor(generateColorChallenge({ rng, seed, level: this.level })); if (CFG.mode === 'pattern') this.setupPattern(generatePatternChallenge({ rng, seed, level: this.level })); if (CFG.mode === 'letter') this.setupLetter(generateLetterChallenge({ rng, seed, level: this.level })); if (CFG.mode === 'memory') this.setupMemory(generateMemoryChallenge({ rng, seed, level: this.level })); if (CFG.mode === 'handwriting') { const c = generateLetterChallenge({ rng, seed, level: this.level }); if (Array.isArray(CFG.answers) && CFG.answers.length) c.answer = CFG.answers[(this.level - 1) % CFG.answers.length]; else if (CFG.answer) c.answer = CFG.answer; this.setupHandwriting(c); } if (CFG.mode === 'paint') this.setupPaint(); window.__APRINCAR_GAME_STATE__ = { mode: CFG.mode, variant: CFG.variant, level: this.level, challenge: this.challenge ?? null, targets: this.testTargets ?? [], inputReady: true }; }
    target(value, x, y, w, h, kind) { this.testTargets.push({ value, x, y, w, h, kind }); }
    addCardButton(x, y, w, h, label, value, color = C.white, kind = 'action') { const box = this.add.rectangle(x, y, w, h, color).setStrokeStyle(2, 0xe2dfd7).setInteractive({ useHandCursor: true }); const text = this.add.text(x, y, label, { fontFamily: FONT, fontSize: `${Math.min(34, h * .42)}px`, fontStyle: 'bold', color: color === C.white ? C.ink : '#ffffff' }).setOrigin(.5); this.roundGroup.add([box, text]); this.target(kind === 'action' ? label : value, x, y, w, h, kind); box.on('pointerup', () => this.choose(value, box)); return box; }
    setupCounting(c) { this.challenge = c; this.selected = 0; if (CFG.variant === 'animals') { this.promptText.setText('Conte os bichos e escolha a quantidade correta'); const cols = Math.min(5, Math.ceil(Math.sqrt(c.items.length))); const rows = Math.ceil(c.items.length / cols); c.items.forEach((_, i) => { const x = 480 - (cols - 1) * 92 / 2 + (i % cols) * 92, y = 240 + Math.floor(i / cols) * 86; this.roundGroup.add(this.add.ellipse(x, y, 58, 44, C.leaf)); }); const optY = rows > 1 ? 485 : 430; c.options.forEach((n, i) => this.addCardButton(390 + (i - (c.options.length - 1) / 2) * 115, optY, 90, 66, String(n), n, C.white, 'choice')); } else if (CFG.variant === 'fruit') { this.promptText.setText(`Coloque ${c.answer} frutas na cesta`); this.counter = this.add.text(480, 450, '0', { fontFamily: FONT, fontSize: '44px', fontStyle: 'bold', color: '#ffffff' }).setOrigin(.5); this.roundGroup.add(this.add.rectangle(480, 450, 270, 110, 0xc98749).setStrokeStyle(5, 0x8f5b2c)); this.roundGroup.add(this.counter); const count = Math.min(10, c.answer + 3); for (let i = 0; i < count; i++) { const x = 210 + (i % 5) * 135, y = 225 + Math.floor(i / 5) * 100, fruit = this.add.circle(x, y, 28, i % 2 ? C.coral : C.sun).setInteractive({ useHandCursor: true }); this.roundGroup.add(fruit); this.target(`fruit-${i + 1}`, x, y, 56, 56, 'toggle'); fruit.on('pointerup', () => this.togglePick(fruit, x, y)); } const check = this.addCardButton(480, 535, 190, 58, 'Conferir', '__check__'); check.removeAllListeners('pointerup'); check.on('pointerup', () => this.submitResult(this.selected === c.answer, { selected: this.selected, target: c.answer })); } else { this.promptText.setText(`Monte uma torre com ${c.answer} blocos`); for (let i = 0; i < 10; i++) { const x = 170 + (i % 5) * 145, y = 220 + Math.floor(i / 5) * 90, block = this.add.rectangle(x, y, 72, 62, [C.purple, C.coral, C.sun, C.leaf, C.sky][i % 5]).setInteractive({ useHandCursor: true }); this.roundGroup.add(block); this.target(`block-${i + 1}`, x, y, 72, 62, 'toggle'); block.on('pointerup', () => this.togglePick(block, x, y)); } const check = this.addCardButton(780, 500, 150, 58, 'Conferir', '__check__'); check.removeAllListeners('pointerup'); check.on('pointerup', () => this.submitResult(this.selected === c.answer, { selected: this.selected, target: c.answer })); } }
    togglePick(object, x, y) { const picked = !object.getData('picked'); object.setData('picked', picked); this.selected += picked ? 1 : -1; this.counter?.setText(String(this.selected)); this.tweens.add({ targets: object, scale: picked ? .82 : 1, alpha: picked ? .72 : 1, duration: 240 }); this.updateState({ selectedCount: this.selected }); }
    setupColor(c) { this.challenge = c; this.promptText.setText(`Leve a peça até a cor ${c.label}`); const piece = this.add.circle(180, 320, 54, COLOR_HEX[c.answer]).setInteractive({ draggable: true }); this.input.setDraggable(piece); this.roundGroup.add(piece); this.target('source', 180, 320, 108, 108, 'drag-source'); const slots = []; c.options.forEach((color, i) => { const x = 430 + i * 135, slot = this.add.rectangle(x, 320, 105, 115, COLOR_HEX[color], .22).setStrokeStyle(4, COLOR_HEX[color]); slot.setData('color', color); this.roundGroup.add(slot); this.target(color, x, 320, 105, 115, 'drop-zone'); slots.push(slot); }); this.input.on('drag', (p, o, x, y) => { o.x = x; o.y = y; }); this.input.on('dragend', (p, o) => { if (o !== piece) return; const hit = slots.find(s => Phaser.Geom.Intersects.CircleToRectangle(new Phaser.Geom.Circle(piece.x, piece.y, 40), s.getBounds())); const ok = !!hit && hit.getData('color') === c.answer; this.submitResult(ok, { target: c.answer, selected: hit?.getData('color') ?? null }); if (!ok) this.tweens.add({ targets: piece, x: 180, y: 320, duration: 300 }); }); }
    setupPattern(c) { this.challenge = c; this.promptText.setText('Qual peça continua o padrão?'); const palette = [C.purple, C.coral, C.sun, C.leaf, C.sky], map = { '●': 0, '▲': 1, '■': 2, '◆': 3, '★': 4 }; c.sequence.forEach((token, i) => this.roundGroup.add(this.add.text(210 + i * 70, 280, token, { fontFamily: FONT, fontSize: '52px', color: '#6f5bd7' }).setOrigin(.5))); c.options.forEach((t, i) => this.addCardButton(360 + i * 115, 430, 90, 76, t, t, palette[map[t] ?? 0], 'choice')); }
    setupLetter(c) { this.challenge = c; this.promptText.setText(`Encontre a letra ${c.answer}`); const positions = Phaser.Utils.Array.Shuffle([{ x: 240, y: 250 }, { x: 410, y: 230 }, { x: 580, y: 260 }, { x: 735, y: 235 }, { x: 320, y: 400 }, { x: 500, y: 410 }, { x: 680, y: 390 }]).slice(0, c.options.length); c.options.forEach((letter, i) => { const p = positions[i], circle = this.add.circle(p.x, p.y, 54, [C.purple, C.coral, C.sun, C.leaf, C.sky][i % 5]).setInteractive({ useHandCursor: true }); this.roundGroup.add([circle, this.add.text(p.x, p.y, letter, { fontFamily: FONT, fontSize: '48px', fontStyle: 'bold', color: '#ffffff' }).setOrigin(.5)]); this.target(letter, p.x, p.y, 108, 108, 'choice'); circle.on('pointerup', () => this.choose(letter, circle)); }); }
    setupMemory(c) { this.challenge = c; this.promptText.setText('Encontre todos os pares'); this.memoryOpen = []; this.memoryMatched = 0; this.memoryMoves = 0; const cols = c.pairs <= 6 ? 4 : 5; c.cards.forEach((card, i) => { const x = 480 - (cols - 1) * 135 / 2 + (i % cols) * 135, y = 220 + Math.floor(i / cols) * 112, box = this.add.rectangle(x, y, 115, 92, C.purple).setInteractive({ useHandCursor: true }); const text = this.add.text(x, y, '★', { fontFamily: FONT, fontSize: '40px', color: '#ffffff' }).setOrigin(.5); box.setData('card', card); box.setData('text', text); this.roundGroup.add([box, text]); this.target(card.id, x, y, 115, 92, 'memory-card'); box.on('pointerup', () => this.flipMemory(box)); }); }
    flipMemory(box) { if (this.locked || box.getData('matched') || box.getData('open')) return; const card = box.getData('card'), text = box.getData('text'); box.setData('open', true); text.setText(card.value); this.memoryOpen.push(box); if (this.memoryOpen.length !== 2) return; this.memoryMoves++; this.locked = true; this.updateState({ inputReady: false }); const [a, b] = this.memoryOpen, same = a.getData('card').pairId === b.getData('card').pairId; this.time.delayedCall(480, async () => { if (same) { a.setData('matched', true); b.setData('matched', true); this.memoryMatched++; this.updateState({ matchedPairs: this.memoryMatched, moves: this.memoryMoves }); if (this.memoryMatched === this.challenge.pairs) { this.locked = false; await this.submitResult(true, { moves: this.memoryMoves, pairs: this.challenge.pairs }); } } else { for (const x of [a, b]) { x.setData('open', false); x.getData('text').setText('★'); } this.updateState({ lastResult: 'failure', moves: this.memoryMoves }); await this.recordEvidence(false, { memoryMismatch: true }); } this.memoryOpen = []; this.locked = false; this.updateState({ inputReady: true }); }); }
    setupHandwriting(c) { this.challenge = c; this.promptText.setText(`Desenhe a letra ${c.answer}`); const guideAlpha = Math.max(0.08, 0.34 - (this.level - 1) * 0.045); const guide = this.add.text(235, 330, c.answer, { fontFamily: FONT, fontSize: '250px', fontStyle: 'bold', color: '#8b5cf6' }).setOrigin(.5).setAlpha(guideAlpha); const zone = this.add.rectangle(590, 335, 470, 350, C.white).setStrokeStyle(4, 0xded5ff).setInteractive(); this.handwritingGraphics = this.add.graphics().lineStyle(10, C.blue, .88); this.roundGroup.add([guide, zone, this.handwritingGraphics]); this.strokes = []; let current, previous; zone.on('pointerdown', p => { current = []; previous = { x: p.x, y: p.y }; this.strokes.push(current); current.push(this.normPoint(p, zone)); }); zone.on('pointermove', p => { if (!p.isDown || !current || !previous) return; const point = this.normPoint(p, zone); if (current.length < 220) current.push(point); this.handwritingGraphics.lineBetween(previous.x, previous.y, p.x, p.y); previous = { x: p.x, y: p.y }; }); this.input.on('pointerup', () => { current = null; previous = null; this.updateState({ strokeCount: this.strokes.length }); }); const check = this.addCardButton(790, 535, 170, 58, 'Conferir', '__check__'); check.removeAllListeners('pointerup'); check.on('pointerup', async () => { const result = await aprincar.capability.request('handwriting.evaluate', { symbol: c.answer, strokes: this.strokes }); await this.submitResult(!!result?.recognized, { handwriting: result, symbol: c.answer, guideAlpha }); }); }
    normPoint(p, zone) { const b = zone.getBounds(); return { x: (p.x - b.left) / b.width, y: (p.y - b.top) / b.height, t: Date.now() }; }
    setupPaint() { this.promptText.setText('Crie do seu jeito — não existe resposta errada'); const canvas = this.add.rectangle(500, 335, 690, 390, C.white).setStrokeStyle(3, 0xe2dfd7).setInteractive(); this.paintGraphics = this.add.graphics().lineStyle(12, C.blue, .9); this.roundGroup.add([canvas, this.paintGraphics]); this.paintStrokes = []; let current = null, previous = null; canvas.on('pointerdown', p => { current = []; previous = { x: p.x, y: p.y }; this.paintStrokes.push(current); current.push(this.normPoint(p, canvas)); this.updateState({ paintStrokeCount: this.paintStrokes.length }); }); canvas.on('pointermove', p => { if (!p.isDown || !current || !previous) return; const totalPoints = this.paintStrokes.reduce((sum, stroke) => sum + stroke.length, 0); if (totalPoints < 400) current.push(this.normPoint(p, canvas)); this.paintGraphics.lineBetween(previous.x, previous.y, p.x, p.y); previous = { x: p.x, y: p.y }; }); this.input.on('pointerup', () => { current = null; previous = null; }); const save = this.addCardButton(800, 540, 180, 56, 'Guardar desenho', 'Guardar desenho'); save.removeAllListeners('pointerup'); save.on('pointerup', async () => { await aprincar.storage.set('paint:last', { strokes: this.paintStrokes, savedAt: new Date().toISOString() }); this.attempts++; await aprincar.evidence.submit({ skillId: CFG.skillId, result: 'observed', independent: true, assistance: 'none', difficulty: .2, confidence: .85, attempts: this.attempts, metadata: { level: this.level, creative: true, strokeCount: this.paintStrokes.length } }); this.statusText.setText('Desenho guardado ✨'); this.updateState({ paintSaved: true, lastResult: 'observed' }); }); }
    choose(value, source) { if (this.locked) return; this.submitResult(value === this.challenge.answer, { selected: value, target: this.challenge.answer, sourceX: source?.x }); }
    async recordEvidence(ok, metadata = {}) { this.attempts++; return aprincar.evidence.submit({ skillId: CFG.skillId, result: ok ? 'success' : 'failure', independent: true, assistance: 'none', difficulty: this.challenge?.difficulty ?? .35, confidence: ok ? .92 : .8, attempts: this.attempts, metadata: { level: this.level, ...metadata } }); }
    async submitResult(ok, metadata = {}) { if (this.locked) return; this.locked = true; this.updateState({ lastResult: ok ? 'success' : 'failure', inputReady: false }); await this.recordEvidence(ok, metadata); if (ok) { await aprincar.rewards.request({ reason: `${CFG.mode}-round`, amount: 2 }); this.time.delayedCall(900, () => { this.level++; this.nextRound(); }); } else { this.locked = false; this.updateState({ inputReady: true }); } }
  }
  new Phaser.Game({ type: Phaser.AUTO, width: 960, height: 640, parent: 'game', backgroundColor: '#f7f6f2', scene: [AprincarScene], scale: { mode: Phaser.Scale.FIT, autoCenter: Phaser.Scale.CENTER_BOTH }, input: { activePointers: 3 }, render: { antialias: true } });
})();
