import type { SkillDefinition } from '../../extension-contracts/src/types.ts';
export const SKILLS: SkillDefinition[] = [
  {
    id: 'perception.colors.match',
    domain: 'perception',
    area: 'colors',
    label: { 'pt-BR': 'Relacionar cores' },
    description: { 'pt-BR': 'Relaciona cores iguais.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 2, max: 5 },
  },
  {
    id: 'perception.colors.name',
    domain: 'perception',
    area: 'colors',
    label: { 'pt-BR': 'Reconhecer cores' },
    description: { 'pt-BR': 'Reconhece e nomeia cores frequentes.' },
    prerequisites: ['perception.colors.match'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 3, max: 6 },
  },
  {
    id: 'perception.shapes.match',
    domain: 'perception',
    area: 'shapes',
    label: { 'pt-BR': 'Relacionar formas' },
    description: { 'pt-BR': 'Relaciona formas geométricas semelhantes.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 2, max: 5 },
  },
  {
    id: 'perception.visual.discrimination',
    domain: 'perception',
    area: 'visual',
    label: { 'pt-BR': 'Discriminação visual' },
    description: { 'pt-BR': 'Percebe semelhanças e diferenças visuais.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 2, max: 7 },
  },
  {
    id: 'motor.tap.control',
    domain: 'motor',
    area: 'pointer',
    label: { 'pt-BR': 'Controle de toque' },
    description: { 'pt-BR': 'Controla toques intencionais na tela.' },
    prerequisites: [],
    evidenceMode: 'observational',
    ageGuidance: { min: 2, max: 5 },
  },
  {
    id: 'motor.drag.control',
    domain: 'motor',
    area: 'pointer',
    label: { 'pt-BR': 'Arrastar com controle' },
    description: { 'pt-BR': 'Arrasta elementos até alvos com controle.' },
    prerequisites: ['motor.tap.control'],
    evidenceMode: 'observational',
    ageGuidance: { min: 2, max: 6 },
  },
  {
    id: 'motor.prewriting.lines',
    domain: 'motor',
    area: 'prewriting',
    label: { 'pt-BR': 'Traços básicos' },
    description: { 'pt-BR': 'Produz linhas e trajetos básicos.' },
    prerequisites: [],
    evidenceMode: 'observational',
    ageGuidance: { min: 3, max: 6 },
  },
  {
    id: 'motor.prewriting.curves',
    domain: 'motor',
    area: 'prewriting',
    label: { 'pt-BR': 'Curvas e contornos' },
    description: { 'pt-BR': 'Produz curvas e contornos com controle.' },
    prerequisites: ['motor.prewriting.lines'],
    evidenceMode: 'observational',
    ageGuidance: { min: 3, max: 7 },
  },
  {
    id: 'motor.free-drawing',
    domain: 'motor',
    area: 'drawing',
    label: { 'pt-BR': 'Desenho livre' },
    description: { 'pt-BR': 'Explora desenho livre com ferramentas digitais.' },
    prerequisites: ['motor.tap.control'],
    evidenceMode: 'observational',
    ageGuidance: { min: 2, max: 10 },
  },
  {
    id: 'logic.classification.one-attribute',
    domain: 'logic',
    area: 'classification',
    label: { 'pt-BR': 'Classificar por um atributo' },
    description: { 'pt-BR': 'Classifica objetos por cor, forma ou outro atributo.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 3, max: 7 },
  },
  {
    id: 'logic.classification.multi-attribute',
    domain: 'logic',
    area: 'classification',
    label: { 'pt-BR': 'Classificar por múltiplos atributos' },
    description: { 'pt-BR': 'Classifica considerando mais de um atributo.' },
    prerequisites: ['logic.classification.one-attribute'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 9 },
  },
  {
    id: 'logic.patterns.ab',
    domain: 'logic',
    area: 'patterns',
    label: { 'pt-BR': 'Padrões AB' },
    description: { 'pt-BR': 'Identifica e completa padrões alternados simples.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 7 },
  },
  {
    id: 'logic.patterns.abc',
    domain: 'logic',
    area: 'patterns',
    label: { 'pt-BR': 'Padrões ABC' },
    description: { 'pt-BR': 'Identifica e completa padrões de três elementos.' },
    prerequisites: ['logic.patterns.ab'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'logic.sequence.order',
    domain: 'logic',
    area: 'sequence',
    label: { 'pt-BR': 'Ordenar sequências' },
    description: { 'pt-BR': 'Ordena elementos em uma sequência lógica.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 9 },
  },
  {
    id: 'math.quantity.subitize-1-3',
    domain: 'math',
    area: 'quantity',
    label: { 'pt-BR': 'Perceber quantidades até 3' },
    description: { 'pt-BR': 'Percebe pequenas quantidades sem contagem explícita.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 3, max: 6 },
  },
  {
    id: 'math.counting.1-3',
    domain: 'math',
    area: 'counting',
    label: { 'pt-BR': 'Contar até 3' },
    description: { 'pt-BR': 'Conta coleções de até três elementos.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 2, max: 5 },
  },
  {
    id: 'math.counting.1-5',
    domain: 'math',
    area: 'counting',
    label: { 'pt-BR': 'Contar até 5' },
    description: { 'pt-BR': 'Conta coleções de até cinco elementos.' },
    prerequisites: ['math.counting.1-3'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 3, max: 6 },
  },
  {
    id: 'math.counting.1-10',
    domain: 'math',
    area: 'counting',
    label: { 'pt-BR': 'Contar até 10' },
    description: { 'pt-BR': 'Conta coleções de até dez elementos.' },
    prerequisites: ['math.counting.1-5'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 7 },
  },
  {
    id: 'math.number-symbol.1-10',
    domain: 'math',
    area: 'number-symbol',
    label: { 'pt-BR': 'Número e quantidade até 10' },
    description: { 'pt-BR': 'Relaciona numeral e quantidade até 10.' },
    prerequisites: ['math.counting.1-10'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 7 },
  },
  {
    id: 'math.compare.quantities',
    domain: 'math',
    area: 'quantity',
    label: { 'pt-BR': 'Comparar quantidades' },
    description: { 'pt-BR': 'Compara coleções em termos de mais, menos ou igual.' },
    prerequisites: ['math.counting.1-5'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 8 },
  },
  {
    id: 'math.addition.concrete',
    domain: 'math',
    area: 'operations',
    label: { 'pt-BR': 'Adição concreta' },
    description: { 'pt-BR': 'Resolve adições simples manipulando objetos.' },
    prerequisites: ['math.counting.1-10'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'math.subtraction.concrete',
    domain: 'math',
    area: 'operations',
    label: { 'pt-BR': 'Subtração concreta' },
    description: { 'pt-BR': 'Resolve subtrações simples retirando objetos.' },
    prerequisites: ['math.counting.1-10'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'math.geometry.plane-shapes',
    domain: 'math',
    area: 'geometry',
    label: { 'pt-BR': 'Formas planas' },
    description: { 'pt-BR': 'Reconhece círculo, quadrado, triângulo e retângulo.' },
    prerequisites: ['perception.shapes.match'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 3, max: 7 },
  },
  {
    id: 'math.geometry.solids',
    domain: 'math',
    area: 'geometry',
    label: { 'pt-BR': 'Sólidos geométricos' },
    description: { 'pt-BR': 'Distingue sólidos geométricos em contextos concretos.' },
    prerequisites: ['math.geometry.plane-shapes'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 9 },
  },
  {
    id: 'language.vocabulary.everyday',
    domain: 'language',
    area: 'vocabulary',
    label: { 'pt-BR': 'Vocabulário cotidiano' },
    description: { 'pt-BR': 'Amplia vocabulário de objetos e situações cotidianas.' },
    prerequisites: [],
    evidenceMode: 'observational',
    ageGuidance: { min: 2, max: 8 },
  },
  {
    id: 'language.story.sequence',
    domain: 'language',
    area: 'narrative',
    label: { 'pt-BR': 'Sequência narrativa' },
    description: { 'pt-BR': 'Organiza acontecimentos de uma história.' },
    prerequisites: ['logic.sequence.order'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 9 },
  },
  {
    id: 'language.listen.instructions',
    domain: 'language',
    area: 'oral',
    label: { 'pt-BR': 'Compreender instruções' },
    description: { 'pt-BR': 'Compreende instruções orais simples.' },
    prerequisites: [],
    evidenceMode: 'observational',
    ageGuidance: { min: 2, max: 7 },
  },
  {
    id: 'language.describe.attributes',
    domain: 'language',
    area: 'oral',
    label: { 'pt-BR': 'Descrever características' },
    description: { 'pt-BR': 'Descreve características perceptíveis de objetos e personagens.' },
    prerequisites: [],
    evidenceMode: 'observational',
    ageGuidance: { min: 3, max: 8 },
  },
  {
    id: 'phonology.rhyme.recognition',
    domain: 'literacy',
    area: 'phonology',
    label: { 'pt-BR': 'Reconhecer rimas' },
    description: { 'pt-BR': 'Reconhece palavras que rimam.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 7 },
  },
  {
    id: 'phonology.syllable.segment',
    domain: 'literacy',
    area: 'phonology',
    label: { 'pt-BR': 'Segmentar sílabas' },
    description: { 'pt-BR': 'Percebe e segmenta palavras em sílabas.' },
    prerequisites: ['phonology.rhyme.recognition'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 7 },
  },
  {
    id: 'phonology.initial-sound',
    domain: 'literacy',
    area: 'phonology',
    label: { 'pt-BR': 'Som inicial' },
    description: { 'pt-BR': 'Identifica o som inicial de palavras.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 7 },
  },
  {
    id: 'phonology.final-sound',
    domain: 'literacy',
    area: 'phonology',
    label: { 'pt-BR': 'Som final' },
    description: { 'pt-BR': 'Identifica sons finais em palavras familiares.' },
    prerequisites: ['phonology.initial-sound'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'phonology.phoneme.isolate',
    domain: 'literacy',
    area: 'phonology',
    label: { 'pt-BR': 'Isolar fonema' },
    description: { 'pt-BR': 'Isola fonemas em palavras simples.' },
    prerequisites: ['phonology.initial-sound'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'literacy.letter.recognition',
    domain: 'literacy',
    area: 'letters',
    label: { 'pt-BR': 'Reconhecer letras' },
    description: { 'pt-BR': 'Reconhece letras do alfabeto.' },
    prerequisites: [],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 7 },
  },
  {
    id: 'literacy.letter.sound',
    domain: 'literacy',
    area: 'letters',
    label: { 'pt-BR': 'Relacionar letra e som' },
    description: { 'pt-BR': 'Relaciona grafemas a sons frequentes.' },
    prerequisites: ['literacy.letter.recognition', 'phonology.initial-sound'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'literacy.letter.case',
    domain: 'literacy',
    area: 'letters',
    label: { 'pt-BR': 'Maiúsculas e minúsculas' },
    description: { 'pt-BR': 'Relaciona formas maiúsculas e minúsculas.' },
    prerequisites: ['literacy.letter.recognition'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'literacy.word.image',
    domain: 'literacy',
    area: 'words',
    label: { 'pt-BR': 'Palavra e imagem' },
    description: { 'pt-BR': 'Relaciona palavras familiares às imagens correspondentes.' },
    prerequisites: ['literacy.letter.sound'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'writing.trace-letter',
    domain: 'writing',
    area: 'letters',
    label: { 'pt-BR': 'Traçar letras' },
    description: { 'pt-BR': 'Traça letras seguindo guia visual.' },
    prerequisites: ['motor.prewriting.lines', 'motor.prewriting.curves'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 4, max: 7 },
  },
  {
    id: 'writing.copy-letter',
    domain: 'writing',
    area: 'letters',
    label: { 'pt-BR': 'Copiar letras' },
    description: { 'pt-BR': 'Copia letras a partir de um modelo.' },
    prerequisites: ['writing.trace-letter'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'writing.free-letter',
    domain: 'writing',
    area: 'letters',
    label: { 'pt-BR': 'Escrever letras' },
    description: { 'pt-BR': 'Produz letras sem tracing completo.' },
    prerequisites: ['writing.copy-letter'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'writing.copy-word',
    domain: 'writing',
    area: 'words',
    label: { 'pt-BR': 'Copiar palavras' },
    description: { 'pt-BR': 'Copia palavras curtas e familiares.' },
    prerequisites: ['writing.free-letter'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 6, max: 9 },
  },
  {
    id: 'writing.write-name',
    domain: 'writing',
    area: 'words',
    label: { 'pt-BR': 'Escrever o próprio nome' },
    description: { 'pt-BR': 'Registra o próprio nome com crescente autonomia.' },
    prerequisites: ['writing.free-letter'],
    evidenceMode: 'observational',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'reading.decode-syllable',
    domain: 'reading',
    area: 'decoding',
    label: { 'pt-BR': 'Decodificar sílabas' },
    description: { 'pt-BR': 'Combina relações letra-som para ler sílabas simples.' },
    prerequisites: ['literacy.letter.sound'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 8 },
  },
  {
    id: 'reading.decode-word',
    domain: 'reading',
    area: 'decoding',
    label: { 'pt-BR': 'Decodificar palavras' },
    description: { 'pt-BR': 'Lê palavras simples por decodificação.' },
    prerequisites: ['reading.decode-syllable'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 6, max: 9 },
  },
  {
    id: 'creativity.visual-expression',
    domain: 'creativity',
    area: 'visual',
    label: { 'pt-BR': 'Expressão visual' },
    description: { 'pt-BR': 'Explora escolhas visuais em produções próprias.' },
    prerequisites: ['motor.free-drawing'],
    evidenceMode: 'observational',
    ageGuidance: { min: 2, max: 10 },
  },
  {
    id: 'computing.sequence.commands',
    domain: 'computing',
    area: 'algorithms',
    label: { 'pt-BR': 'Sequenciar comandos' },
    description: { 'pt-BR': 'Organiza comandos simples para atingir um objetivo.' },
    prerequisites: ['logic.sequence.order'],
    evidenceMode: 'assessable',
    ageGuidance: { min: 5, max: 10 },
  },
];

const INDEX = new Map(SKILLS.map((skill) => [skill.id, skill]));
export function getSkill(id: string): SkillDefinition | undefined {
  return INDEX.get(id);
}
export function hasSkill(id: string): boolean {
  return INDEX.has(id);
}
export function skillsByDomain(domain: string): SkillDefinition[] {
  return SKILLS.filter((skill) => skill.domain === domain);
}
