export const games = [
  { slug:'counting-animals', id:'aprincar.counting-animals', name:'Conte os Bichos', description:'Conte bichos animados e escolha a quantidade correta.', mode:'counting', variant:'animals', skillId:'math.counting.1-10', ages:[4,7], interests:['math','counting','animals'], playType:'learning', permissions:[] },
  { slug:'fruit-basket', id:'aprincar.fruit-basket', name:'Cesta de Frutas', description:'Escolha a quantidade pedida e leve as frutas até a cesta.', mode:'counting', variant:'fruit', skillId:'math.counting.1-10', ages:[4,7], interests:['math','counting','fruits'], playType:'learning', permissions:[] },
  { slug:'block-tower', id:'aprincar.block-tower', name:'Torre de Blocos', description:'Monte torres com a quantidade certa de blocos.', mode:'counting', variant:'blocks', skillId:'math.counting.1-10', ages:[4,7], interests:['math','counting','construction'], playType:'learning', permissions:[] },
  { slug:'color-match', id:'aprincar.color-match', name:'Mundo das Cores', description:'Leve cada peça até a cor correspondente.', mode:'color', variant:'colors', skillId:'perception.colors.match', ages:[2,6], interests:['colors','logic','drag'], playType:'learning', permissions:[] },
  { slug:'pattern-play', id:'aprincar.pattern-play', name:'Trem dos Padrões', description:'Descubra qual peça continua cada sequência.', mode:'pattern', variant:'train', skillId:'logic.patterns.ab', secondarySkills:['logic.patterns.abc'], ages:[4,8], interests:['logic','patterns'], playType:'learning', permissions:[] },
  { slug:'letter-hunt', id:'aprincar.letter-hunt', name:'Caça às Letras', description:'Encontre letras em movimento e avance por desafios.', mode:'letter', variant:'hunt', skillId:'literacy.letter.recognition', ages:[4,7], interests:['letters','literacy'], playType:'learning', permissions:[] },
  { slug:'write-a', id:'aprincar.write-a', name:'Ateliê de Letras', description:'Desenhe letras com apoio visual que diminui conforme você avança.', mode:'handwriting', variant:'letters', answers:['A','B','V','R','T'], skillId:'writing.trace-letter', ages:[4,8], interests:['letters','writing'], playType:'practice', permissions:['handwriting'] },
  { slug:'paint-free', id:'aprincar.paint-free', name:'Pintura Livre', description:'Desenhe, pinte e experimente sem resposta certa ou errada.', mode:'paint', variant:'creative', skillId:'creativity.visual-expression', ages:[2,10], interests:['paint','creative'], playType:'creative', permissions:['storage'] },
  { slug:'memory-animals', id:'aprincar.memory-animals', name:'Memória dos Bichos', description:'Encontre pares em tabuleiros que crescem automaticamente.', mode:'memory', variant:'animals', skillId:'perception.visual.discrimination', ages:[3,10], interests:['memory','animals','logic'], playType:'practice', permissions:[] },
  { slug:'space-shapes-3d', id:'aprincar.space-shapes-3d', name:'Formas no Espaço 3D', description:'Gire sólidos em 3D e reconheça suas formas.', mode:'three', variant:'geometry', skillId:'math.geometry.solids', ages:[5,10], interests:['geometry','3d','exploration'], playType:'learning', permissions:[] },
];
